[package]
name = "thenexusavenger/enigma"
repository = "https://github.com/TheNexusAvenger/Nexus-Appendage"
description = "Provides SteamVR tracker data to the Roblox client."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "0.5.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["RobloxLibrary/src", "RobloxLibrary/src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]